<?php

declare(strict_types=1);

use App\Organization\Domain\Entity\Organization;

describe('Organization', function (): void {
    describe('creation', function (): void {
        it('is created with owning user id', function (): void {
            $org = new Organization('user-123');
            expect($org->getOwningUsersId())->toBe('user-123');
        });

        it('has null name by default', function (): void {
            $org = new Organization('user-123');
            expect($org->getName())->toBeNull();
        });

        it('returns empty string for id before persistence', function (): void {
            $org = new Organization('user-123');
            // ID is generated by Doctrine when persisted, so it's empty string before persistence
            expect($org->getId())->toBe('');
        });
    });

    describe('name management', function (): void {
        it('can set a name', function (): void {
            $org = new Organization('user-123');
            $org->setName('My Organization');
            expect($org->getName())->toBe('My Organization');
        });

        it('can set name to null', function (): void {
            $org = new Organization('user-123');
            $org->setName('Initial Name');
            $org->setName(null);
            expect($org->getName())->toBeNull();
        });

        it('can update existing name', function (): void {
            $org = new Organization('user-123');
            $org->setName('Original Name');
            $org->setName('Updated Name');
            expect($org->getName())->toBe('Updated Name');
        });
    });
});
